name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: "4.0"
            gemfile: Gemfile
            valgrind: true
          - ruby: 3.4
            gemfile: gemfiles/rails80.gemfile
            os: macos-latest
          - ruby: 3.3
            gemfile: gemfiles/rails72.gemfile
            os: windows-latest
          - ruby: 3.2
            gemfile: gemfiles/rails71.gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v5
      - if: ${{ runner.os == 'macOS' }}
        run: brew install mysql-client
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake compile
      - run: bundle exec rake test

      - uses: ankane/setup-postgres@v1
      - run: bundle exec rake test:postgresql

      - if: ${{ runner.os != 'Windows' }}
        uses: ankane/setup-mysql@v1
      - if: ${{ runner.os != 'Windows' }}
        run: bundle exec rake test:mysql2
      - if: ${{ runner.os != 'Windows' }}
        run: bundle exec rake test:trilogy

      - if: ${{ matrix.valgrind }}
        run: |
          sudo apt-get update && sudo apt-get install valgrind
          bundle exec rake test:valgrind
